### ISSUE TITLE
doen't installed correctly when node is installed via homebrew

### ISSUE THREAD

**Issue by hronro** [pnpm/self-installer#11]
OS: macOS 10.13.6
node: v12.3.0

When you use Homebrew to install node, the install location is `/usr/local/Cellar/node/12.3.0/bin/node`, and then Homebrew create a symlink to `/usr/local/bin/node`.
The problem is, this install script will install pnpm to `/usr/local/Cellar/node/12.3.0/bin/pnpm`, which is not include in the PATH. So after the installation, we still can't use pnpm command in the shell.

**Comment by shirshak55** [comment]
what to do?  We cannot even add /usr/local/Cellar/node/12.3.0/bin/pnpm to path because after upgrading node that folder might change. 

And even worst it is not distributed via homebrew :(

**Comment by zkochan** [comment]
As a temporary solution, you can probably install pnpm via npm (npm i -g pnpm)

**Comment by shirshak55** [comment]
@zkochan how to uninstall it so that there is no leftovers from curl one so we can reinstall via npm?

**Comment by zkochan** [comment]
It is probably in `/usr/local/Cellar/node/12.3.0/lib/node_modules/pnpm`.

This code resolves the destination folder: https://github.com/pnpm/self-installer/blob/70c146f9dcc774dbd514944bdcafdb378aecbcaf/src/installTo.js#L26-L29

**Comment by shirshak55** [comment]
@zkochan hmm you mean this curl only creates those binaries pnpm and pnpx at that folder?
```/usr/local/Cellar/node/12.3.0/lib/node_modules/``` if we delete those did we uninstall it cleanly? I mean are there other leftovers like new files this shell script produces etc?

**Comment by zkochan** [comment]
this shell unpacks pnpm to that folder and adds pnpm/pnpx shell scripts to `/usr/local/Cellar/node/12.3.0/bin/`

**Comment by shirshak55** [comment]
@zkochan Okay but where do global binaries get installed? I tried this
```
pnpm add tslint --global
pnpm install tslint --global
```

it says 

```
➜ pnpm add tslint --global
 WARN  tslint: tsutils@2.29.0 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev || >= 3.0.0-dev || >= 3.1.0-dev but none was installed.
 WARN  tslint@5.20.0 requires a peer of typescript@>=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev || >=3.0.0-dev || >= 3.1.0-dev || >= 3.2.0-dev but none was installed.
Packages: +15
+++++++++++++++
Resolving: total 233, reused 223, downloaded 10, done

/usr/local/Cellar/node/12.11.1/pnpm-global/3:
```

I checked /usr/local/bin but there are no binaries :(

I tried with `pkg` also it is not working.

**Comment by zkochan** [comment]
This issue should not happen anymore with the new installation methods of pnpm: https://pnpm.js.org/en/installation
