### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by shellscape** [pnpm/self-installer#12]
While I was looking for ways to install pnpm that would not anger the Github Actions Windows container, I stumbled upon this. Unfortunately I don't see how this can be used on Windows, and there doesn't appear to be any documentation for that.

**Comment by zkochan** [comment]
Try this https://stackoverflow.com/a/57740217/537682

**Comment by shellscape** [comment]
I should have mentioned that I'm unfortunately locked into using CMD.exe right now, because Github has chosen that in their container. I'm attempting to work around this problem: https://github.com/rollup/plugins/commit/265f3f8d931fda024ac85e56538f1cef0b19afd8/checks

**Comment by shellscape** [comment]
I'm going to close this citing the SO post that has working solutions. Hopefully someone finds this useful. My problems more than likely stem from Github Actions bugs.
