### ISSUE TITLE
Installation error: unexpected end of file

### ISSUE THREAD

**Issue by Madh93** [pnpm/self-installer#14]
Impossible to install `pnpm` since the last week.

### self-installer version:

2.1.0

### Code to reproduce the issue:

    curl -L https://unpkg.com/@pnpm/self-installer | PNPM_VERSION=4.12.1 PNPM_DEST=/tmp/node_modules PNPM_BIN_DEST=/tmp/node_modules/bin node

### Expected behavior:

Exit status code: 0.

### Actual behavior:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    49  100    49    0     0   1689      0 --:--:-- --:--:-- --:--:--  1689
100    60  100    60    0     0   1463      0 --:--:-- --:--:-- --:--:--  1463
100 1237k    0 1237k    0     0  13.5M      0 --:--:-- --:--:-- --:--:-- 13.5M
Downloading https://registry.npmjs.org/pnpm/-/pnpm-4.12.1.tgz
{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:164:17) errno: -5, code: 'Z_BUF_ERROR' }
```

### Additional information:

 - `node -v` prints: v10.17.0
 - OS: Ubuntu 18.04.3 LTS

**Comment by zkochan** [comment]
unpkg seems unreliable. 

try downloading from github:

```
curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
```

**Comment by Madh93** [comment]
Thanks for your quick answer. However, I get the same output :thinking: 


Output:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1186k  100 1186k    0     0  5517k      0 --:--:-- --:--:-- --:--:-- 5517k
Downloading https://registry.npmjs.org/pnpm/-/pnpm-4.12.1.tgz
{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:164:17) errno: -5, code: 'Z_BUF_ERROR' }
```

**Comment by zkochan** [comment]
Oh, I see. Seems like we need to add some retry logic to the self-installer. If the tarball is incorrect, redownload it.

**Comment by zkochan** [comment]
Use `curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm`
