### ISSUE TITLE
Not able to access the URL

### ISSUE THREAD

**Issue by shubhambattoo** [pnpm/self-installer#6]
Not installing while using the command,
`curl -L https://unpkg.com/@pnpm/self-installer | node`

{ [Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/pnpm']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/lib/node_modules/pnpm' }

I am trying to install it on WSL Ubuntu 18.04

**Comment by zkochan** [comment]
What would be the preferred destination in your system? You can change the dest dir by setting the PNPM_DEST and PNPM_BIN_DEST env variables

```
curl -L https://unpkg.com/@pnpm/self-installer | PNPM_DEST=/something PNPM_BIN_DEST=/something/bin node
```
